### ISSUE TITLE
Bei mir startet die Instanz nur noch mit folgender Fehlermeldung

### ISSUE THREAD

**Issue by Merlinberlin61** [TA2k/ioBroker.vaillant#51]
host.pi4-IO-Broker
2024-02-27 13:09:27.594	info	Restart adapter system.adapter.vaillant.0 because enabled
host.pi4-IO-Broker
2024-02-27 13:09:27.593	error	instance system.adapter.vaillant.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

vaillant.0
2024-02-27 13:09:27.067	info	terminating

vaillant.0
2024-02-27 13:09:26.564	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

vaillant.0
2024-02-27 13:09:26.562	info	terminating

vaillant.0
2024-02-27 13:09:26.561	info	cleaned everything up...

vaillant.0
2024-02-27 13:09:26.550	error	Cannot read properties of undefined (reading 'split')

vaillant.0
2024-02-27 13:09:26.549	error	TypeError: Cannot read properties of undefined (reading 'split') at /opt/iobroker/node_modules/iobroker.vaillant/main.js:255:55 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Vaillant.myvLoginv2 (/opt/iobroker/node_modules/iobroker.vaillant/main.js:235:22) at async Vaillant.onReady (/opt/iobroker/node_modules/iobroker.vaillant/main.js:100:7)

vaillant.0
2024-02-27 13:09:26.548	error	unhandled promise rejection: Cannot read properties of undefined (reading 'split')

vaillant.0
2024-02-27 13:09:26.547	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

vaillant.0
2024-02-27 13:09:24.337	info	Generate new Id

vaillant.0
2024-02-27 13:09:24.261	info	starting. Version 0.3.0 in /opt/iobroker/node_modules/iobroker.vaillant, node: v18.19.1, js-controller: 5.0.19

vaillant.0
2024-02-27 14:09:24.337	info	Generate new Id

vaillant.0
2024-02-27 14:09:24.261	info	starting. Version 0.3.0 in /opt/iobroker/node_modules/iobroker.vaillant, node: v18.19.1, js-controller: 5.0.19

**Comment by Merlinberlin61** [comment]
Ich habe schon alle Updates gemacht alle anderen Module laufen einwandfrei. Bis zum letzten Update war auch alles in Ordnung.
