### ISSUE TITLE
Fehler Meldung nach js-controller 3.0.20 update

### ISSUE THREAD

**Issue by MichaWilk** [TA2k/ioBroker.vaillant#6]
2020-05-03 21:41:58.942 - info: vaillant.0 (22821) starting. Version 0.0.8 in /opt/iobroker/node_modules/iobroker.vaillant, node: v12.16.3, js-controller: 3.0.20
--
2020-05-03 21:41:58.983 - info: vaillant.0 (22821) Generate new Id

2020-05-03 21:42:31.244 - warn: vaillant.0 (22821) State value to set is invalid for vaillant.0.21183600202529220938024510N2.spine.currentPVMeteringInfo: The state contains no properties! At least one property is expected!

2020-05-03 21:42:31.246 - warn: vaillant.0 (22821) **This value will not be set in future versions. Please report this to the developer.**

2020-05-03 21:42:41.433 - error: vaillant.0 (22821) uncaught exception: undefined

2020-05-03 21:42:41.435 - error: vaillant.0 (22821) uncaught exception: Cannot read property 'stack' of undefined
2020-05-03 21:42:41.437 - error: vaillant.0 (22821) TypeError: Cannot read property 'stack' of undefined
at process.exceptionHandler (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8238:17)
at process.emit (events.js:310:20)
at processPromiseRejections (internal/process/promises.js:209:33)
at processTicksAndRejections (internal/process/task_queues.js:98:32)

2020-05-03 21:42:41.439 - info: vaillant.0 (22821) cleaned everything up...
2020-05-03 21:42:41.489 - info: vaillant.0 (22821) terminating
2020-05-03 21:42:41.490 - info: vaillant.0 (22821) Terminated (NO_ERROR): Without reason
2020-05-03 21:42:42.035 - info: host.IoBrocker instance system.adapter.vaillant.0 terminated with code 0 (NO_ERROR)
2020-05-03 21:42:42.042 - info: host.IoBrocker Restart adapter system.adapter.vaillant.0 because enabled

**Comment by TA2k** [comment]
please try to install the version from github

**Comment by MichaWilk** [comment]
Danke
